const config = {
  appName: "Hi Dave",
  apiBaseUrl: process.env.NEXTAUTH_URL || "http://localhost:3000",
  environment: process.env.NODE_ENV || "development",
  logo: "/assets/images/png/logo.png",
  logoBlue: "/assets/images/png/logo-blue.png",
  backgroundImage: "/assets/images/png/bg.png",
  googleLogo: "/assets/images/png/google.png",
  dashboardSvg: "/assets/images/svg/icon_dashboard.svg",
  serviceSvg: "/assets/images/svg/icon_service.svg",
  billingSvg: "/assets/images/svg/icon_billing.svg",
  ticketSvg: "/assets/images/svg/icon_ticket.svg",
  computerSvg: "/assets/images/svg/icon_computer.svg",
  billSvg: "/assets/images/svg/icon_bill.svg",
  profileSvg: "/assets/images/svg/icon_profile.svg",
  arrowRightSvg: "/assets/images/svg/arrow-right-white.svg",
  dotBarSuccessSvg: "/assets/images/svg/dotbar_success.svg",
  dotBarDarkSvg: "/assets/images/svg/dotbar_dark.svg",
  searchSvg: "/assets/images/svg/search.svg",
  arrowRightNormalSvg: "/assets/images/svg/icon_arrow_right.svg",
  blueLogoSvg: "/assets/images/svg/blue-logo.svg",
  shareSvg: "/assets/images/svg/icon_share.svg",
  notifPng: "/assets/images/png/icon-notif.png",
  avatarPng: "/assets/images/png/avatar.png",
  onBoardingPng: "/assets/images/png/onboarding.png",
};

export default config;
