export const DUMMY_SERVICE = [
  {
    id: "s1",
    name: "Dave Free Trial",
    text: "free trial",
    service_plan: "active",
    until: "30/12/2024",
    content: "Cloud 03 - L 10 users",
    preparing_percentage: "",
    status: "free_trial",
  },
  {
    id: "s2",
    name: "Dave Service 2",
    text: "preparing process",
    service_plan: "pro plan",
    until: "30/12/2024",
    content: "Cloud 03 - L 10 users",
    preparing_percentage: 90,
    status: "preparing_process",
  },
  {
    id: "s3",
    name: "Dave Service 3",
    text: "waiting payment",
    service_plan: "pro plan",
    until: "30/12/2024",
    content: "Cloud 03 - L 10 users",
    preparing_percentage: "",
    status: "waiting_payment",
  },
  {
    id: "s4",
    name: "Dave Service 4",
    text: "need extend",
    service_plan: "pro plan",
    until: "30/12/2024",
    content: "Cloud 03 - L 10 users",
    preparing_percentage: "",
    status: "need_extend",
  },
  {
    id: "s5",
    name: "Dave Service 5",
    text: "",
    service_plan: "pro plan",
    until: "30/12/2024",
    content: "Cloud 03 - L 10 users",
    preparing_percentage: "",
    status: "active",
  },
  {
    id: "s6",
    name: "Dave Service 6",
    text: "",
    service_plan: "pro plan",
    until: "30/12/2024",
    content: "Cloud 03 - L 10 users",
    preparing_percentage: "",
    status: "active",
  },
  {
    id: "s7",
    name: "Dave Service 7",
    text: "stopped",
    service_plan: "active",
    until: "30/12/2024",
    content: "Cloud 03 - L 10 users",
    preparing_percentage: "",
    status: "stopped",
  },
  {
    id: "s8",
    name: "Dave Service 8",
    text: "",
    service_plan: "pro plan",
    until: "30/12/2024",
    content: "Cloud 03 - L 10 users",
    preparing_percentage: "",
    status: "active",
  },  
];
